Refactor all code into ./tx

diff --git a/texcellent b/texcellent
--- a/texcellent
+++ b/texcellent
@@ -16,9 +16,8 @@
 #
 
 # TODO: Update usage guide
-source $TEXCELLENT_DIR/utils/usage 
 
-function check_command () {
+check_command () {
     if ! command -v "$1" &> /dev/null; then
         echo "Missing dependency: $1"
         return 1
@@ -26,9 +25,11 @@ function check_command () {
     return 0
 }
 
-tx () { texcellent "$@" }
-function texcellent () {
-    if [[ $# -eq 0 ]]; then usage_help; return 1; fi
+# TODO: List info of project file: tx <file>
+
+#tx () { texcellent "$@" }
+texcellent () {
+    if [[ $# -eq 0 ]]; then \. $TEXCELLENT_DIR/utils/usage; return 1; fi
 
     flag_count=0
     flag_new_project=0
@@ -41,40 +42,18 @@ function texcellent () {
     template="basic"
 
     # Parse all flags
-    while getopts ":hcpfolLTO" opt; do
+    while getopts ":hclLTpfOo" opt; do
         case $opt in
-            h) # Help (aborts rest of commands)
-                usage_help
-                return 0
-                ;;
-            c) # Count words in file (1 arg -> filename)
-                flag_count=1    
-                break
-                ;;
-            p) # New project (1 arg -> project_name)
-                flag_new_project=1
-                ;;
-            f) # New file (1 arg -> file_name)
-                flag_new_file=1
-                ;;
-            o) # Open project (no args, end of command)
-                flag_open=1
-                ;;
-            l) # List all templates
-                flag_list=1
-                ;;
-            L) # List contents of all templates
-                flag_list_long=1
-                ;;
-            T) # Add new template from file/directory
-                flag_new_template=1
-                ;;
-            O) # Output content as text
-                flag_output=1
-                ;;
-            \?)
-                echo Invalid option: -$OPTARG >&2
-                ;;
+            h) usage_help; return 0;;
+            c) flag_count=1; break;;
+            l) flag_list=1; break;;
+            L) flag_list_long=1; break;;
+            T) flag_new_template=1; break;;
+            p) flag_new_project=1;;
+            f) flag_new_file=1;;
+            O) flag_output=1;;
+            o) flag_open=1;;
+            \?) echo Invalid option: -$OPTARG >&2;;
         esac
     done
 
@@ -86,6 +65,8 @@ function texcellent () {
     # Remove this?
 
     # Count words in directory / file
+    # TODO: Option to exclude main.tex
+    # TODO: pdftotxt ?
     if [ $flag_count -ne 0 ]; then
         if ! check_command "detex"; then return 1; fi
         if ! check_command "wc"; then return 1; fi
@@ -137,40 +118,27 @@ function texcellent () {
         output_file="out.txt"
         if [[ $# -ge 2 && -n $2 ]]; then output_file=$2; fi
         if [[ -d $1 && -n $1 ]]; then  
-            echo "DIR"
-            return 0
+            echo "DIR currently not working"
         elif [[ -s $1 && -n $1 ]]; then
             echo "FILE"
             detex $1 >> $output_file
-            return 0
+            file_path=$output_file
+        else
+            echo "Error: Not a valid directory or file"
         fi
-
-        echo "Error: Not a valid directory or file"
-        return 1
     fi
         
     # Create a new project / file
     if [ $flag_new_project -ne 0 ]; then 
         if ! check_command "cp"; then return 1; fi
         cp -a "$TEXCELLENT_DIR/templates/projects/$template" "./$1"
+        file_path="./$1"
     elif [ $flag_new_file -ne 0 ]; then
         if ! check_command "cp"; then return 1; fi
         cp "$TEXCELLENT_DIR/templates/files/$template.tex" "$1.tex"
         cp "$TEXCELLENT_DIR/utils/tex-vimrc" ".vimrc"
-        #touch "./$1.tex" 
-        #cat "$TEXCELLENT_DIR/templates/files/$template.tex" >> "./$1.tex"
-        #touch "./.vimrc"
-        #cat "TEXCELLENT_DIR/utils/text-vimrc" >> "./.vimrc"
+        file_path="$1.tex"
     fi
-
-        #file_path="./$1"
-        #file_path="."
-    #if (( ${+file_path} )); then
-        #touch "$file_path/$1.tex"
-        #cat "$TEXCELLENT_DIR/templates/$template.tex" >> "$file_path/$1.tex"
-        #touch "$file_path/.vimrc"
-        #cat "$TEXCELLENT_DIR/utils/tex-vimrc" >> "$file_path/.vimrc"
-    #fi
 
     # Open project if flag and path is set
     if [ $flag_open -ne 0 ]; then 
